{title: Invocazione alla SS.ma Trinità}

V/ A TE LODE, A TE GLORIA, A TE GRAZIE NEI SECOLI, O BEATA TRINITÀ.
R/ SANTA, SANTO, SANTO, IL SIGNORE DIO DELL'UNIVERSO I CIELI E LA TERRA SONO PIENI DELLA TUA GLORIA.
V/ GLORIA AL PADRE, E AL FIGLIO, E ALLO SPIRITO SANTO.
R/ COME ERA NEL PRINCIPIO E ORA E SEMPRE NEI SECOLI DEI SECOLI. AMEN.
V/ O DIO SANTO, O DIO FORTE, O DIO IMMORTALE R/ ABBI PIETA DI NOI.
V/ TI SALUTIAMO MARIA.
R/ FIGLIA DI DIO PADRE, MADRE DI DIO FIGLIO SPOSA DELLO SPIRITO SANTO, SANTUARIO DELLA SANTISSIMA TRINITÀ.
V/ BENEDETTA,
R/ LA SANTA TRINITÀ CHE CREA E GORVERNA L'UNIVERSO, BENEDETTA ORA E SEMPRE.